# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


#from _typeshed import Self
from typing import Text
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(361, 588)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Outputlabel = QtWidgets.QLabel(self.centralwidget)
        self.Outputlabel.setGeometry(QtCore.QRect(10, 10, 341, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Outputlabel.setFont(font)
        self.Outputlabel.setFrameShape(QtWidgets.QFrame.Box)
        self.Outputlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Outputlabel.setObjectName("Outputlabel")
        self.percentButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("%"))
        self.percentButton.setGeometry(QtCore.QRect(10, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.percentButton.setFont(font)
        self.percentButton.setObjectName("percentButton")
        self.cbutton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("C"))
        self.cbutton.setGeometry(QtCore.QRect(100, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.cbutton.setFont(font)
        self.cbutton.setObjectName("cbutton")
        self.errorbutton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.remove_it())
        self.errorbutton.setGeometry(QtCore.QRect(190, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.errorbutton.setFont(font)
        self.errorbutton.setObjectName("errorbutton")
        self.devidebutton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("/"))
        self.devidebutton.setGeometry(QtCore.QRect(275, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.devidebutton.setFont(font)
        self.devidebutton.setObjectName("devidebutton")
        self.eightbutton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("8"))
        self.eightbutton.setGeometry(QtCore.QRect(100, 200, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.eightbutton.setFont(font)
        self.eightbutton.setObjectName("eightbutton")
        self.multiplybutton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("*"))
        self.multiplybutton.setGeometry(QtCore.QRect(275, 200, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.multiplybutton.setFont(font)
        self.multiplybutton.setObjectName("multiplybutton")
        self.sevenbutton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("7"))
        self.sevenbutton.setGeometry(QtCore.QRect(10, 200, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.sevenbutton.setFont(font)
        self.sevenbutton.setObjectName("sevenbutton")
        self.ninebutton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("9"))
        self.ninebutton.setGeometry(QtCore.QRect(190, 200, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.ninebutton.setFont(font)
        self.ninebutton.setObjectName("ninebutton")
        self.fivebutton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("5"))
        self.fivebutton.setGeometry(QtCore.QRect(100, 290, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.fivebutton.setFont(font)
        self.fivebutton.setObjectName("fivebutton")
        self.minusbutton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("-"))
        self.minusbutton.setGeometry(QtCore.QRect(275, 290, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.minusbutton.setFont(font)
        self.minusbutton.setObjectName("minusbutton")
        self.fourbutton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("4"))
        self.fourbutton.setGeometry(QtCore.QRect(10, 290, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.fourbutton.setFont(font)
        self.fourbutton.setObjectName("fourbutton")
        self.sixbutton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("6"))
        self.sixbutton.setGeometry(QtCore.QRect(190, 290, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.sixbutton.setFont(font)
        self.sixbutton.setObjectName("sixbutton")
        self.twobutton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("2"))
        self.twobutton.setGeometry(QtCore.QRect(100, 370, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.twobutton.setFont(font)
        self.twobutton.setObjectName("twobutton")
        self.addbutton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("+"))
        self.addbutton.setGeometry(QtCore.QRect(275, 370, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.addbutton.setFont(font)
        self.addbutton.setObjectName("addbutton")
        self.onebutton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("1"))
        self.onebutton.setGeometry(QtCore.QRect(10, 370, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.onebutton.setFont(font)
        self.onebutton.setObjectName("onebutton")
        self.threebutton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("3"))
        self.threebutton.setGeometry(QtCore.QRect(190, 370, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.threebutton.setFont(font)
        self.threebutton.setObjectName("threebutton")
        self.zerobutton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("0"))
        self.zerobutton.setGeometry(QtCore.QRect(100, 450, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.zerobutton.setFont(font)
        self.zerobutton.setObjectName("zerobutton")
        self.equalbutton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.math_it())
        self.equalbutton.setGeometry(QtCore.QRect(275, 450, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.equalbutton.setFont(font)
        self.equalbutton.setObjectName("equalbutton")
        self.plusminusbutton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.plus_minus_it())
        self.plusminusbutton.setGeometry(QtCore.QRect(10, 450, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.plusminusbutton.setFont(font)
        self.plusminusbutton.setObjectName("plusminusbutton")
        self.decimalbutton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.dot_it())
        self.decimalbutton.setGeometry(QtCore.QRect(190, 450, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.decimalbutton.setFont(font)
        self.decimalbutton.setObjectName("decimalbutton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 361, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def remove_it(self):
        screen=self.Outputlabel.text()
        screen=screen[:-1]
        self.Outputlabel.setText(screen)

    def math_it(self):
        screen=self.Outputlabel.text()
        try:
            answer= eval(screen)
            self.Outputlabel.setText(str(answer))
        except:
            self.Outputlabel.setText("Error")

    def plus_minus_it(self):
        screen=self.Outputlabel.text()
        if "-" in screen:
            self.Outputlabel.setText(screen.replace("-",""))
        else:
            self.Outputlabel.setText(f'-{screen}')


    def dot_it(self):
        screen= self.Outputlabel.text()

        if screen[-1]== ".":
            pass
        else:
            self.Outputlabel.setText(f'{screen}.')

    def press_it(self,pressed):
        screen=self.Outputlabel.text()
          
        if pressed=="C":
            self.Outputlabel.setText("0")
        else:
            if self.Outputlabel.text()=="0":
                self.Outputlabel.setText("") 
                
                if pressed	== "=" and len(screen)>8:
                    self.Outputlabel.setText("Error")
            self.Outputlabel.setText(f'{self.Outputlabel.text()}{pressed}')



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.Outputlabel.setText(_translate("MainWindow", "0"))
        self.percentButton.setText(_translate("MainWindow", "%"))
        self.cbutton.setText(_translate("MainWindow", "AC"))
        self.errorbutton.setText(_translate("MainWindow", "C"))
        self.devidebutton.setText(_translate("MainWindow", "/"))
        self.eightbutton.setText(_translate("MainWindow", "8"))
        self.multiplybutton.setText(_translate("MainWindow", "x"))
        self.sevenbutton.setText(_translate("MainWindow", "7"))
        self.ninebutton.setText(_translate("MainWindow", "9"))
        self.fivebutton.setText(_translate("MainWindow", "5"))
        self.minusbutton.setText(_translate("MainWindow", "-"))
        self.fourbutton.setText(_translate("MainWindow", "4"))
        self.sixbutton.setText(_translate("MainWindow", "6"))
        self.twobutton.setText(_translate("MainWindow", "2"))
        self.addbutton.setText(_translate("MainWindow", "+"))
        self.onebutton.setText(_translate("MainWindow", "1"))
        self.threebutton.setText(_translate("MainWindow", "3"))
        self.zerobutton.setText(_translate("MainWindow", "0"))
        self.equalbutton.setText(_translate("MainWindow", "="))
        self.plusminusbutton.setText(_translate("MainWindow", "+/-"))
        self.decimalbutton.setText(_translate("MainWindow", "."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
